### ISSUE TITLE
Add torrent with Label

### ISSUE THREAD

**Issue by Nokoff** [sbussetti/deluge-siphon#12]
Good day Sir, sorry for creating an "issue", I only wanted to contact you directly to request the ability to set the Label of torrent before sending to Deluge. This is similar functionality offered by other popular torrent client chrome extensions such as the utorrent one. Thank you for your work on this so far! Many people appreciate it, and so do I!

Thank you for your time
Regards, Nokoff

**Comment by TimDowker** [comment]
Is this still on the drawing board?

**Comment by scatat** [comment]
If you can add label support, then I'd make a reasonable donation - say 5 USD for this? Not sure how much motivation this is. If a few more could support me in this, then I'm sure Mr Busetti would be kind enough to add the feature. Thanks for a great extension by the way!

**Comment by xDiglett** [comment]
Any updates on this?

**Comment by sbussetti** [comment]
I am, in fact, working on getting this feature implemented -- no donations needed.  Progress is a little slow due to all my other commitments, but being able to add labels is definitely in the works for the next update.

**Comment by scatat** [comment]
Why thanks Steve - would still  be happy to make a contribution though.

**Comment by sbussetti** [comment]
just released version 0.70.0 -- it doesn't include this feature yet, but I set the foundation for this.

**Comment by scatat** [comment]
Thanks ever so much! Looking forward to this feature.

**Comment by sbussetti** [comment]
@scatat  @reinierkors @Nokoff  Version 0.70.3 lets you specify a label from the list of labels you already have in deluge when adding a new torrent.

**Comment by scatat** [comment]
You are the BEST. Thanks ever so much .

**Comment by scatat** [comment]
I just realised I hadn't Starred your project already. Should have done this years ago. Your tool has saved me so much hassle. Thanks again.

**Comment by sbussetti** [comment]
Thanks for using.  It looks like Google's publishing dashboard is running a little slow today, but the new version is queued for distribution, so you'll have it today as soon as they let it out the door.
