### ISSUE TITLE
Associate .torrent files with Deluge Siphon

### ISSUE THREAD

**Issue by admirau** [sbussetti/deluge-siphon#14]
Is there any way to associate .torrent files to automatically handle them via Deluge Siphon?
(eg. click on file on the disk = opens chrome and sends file to Deluge Queue)

**Comment by sbussetti** [comment]
I investigated this, and it does not seem possible to associate files on your desktop with a specific extension.  If you can find an example of an extension that has this behavior, please point it out to me and re-open this issue.
