### ISSUE TITLE
Error: cannot import name_URI

### ISSUE THREAD

**Issue by MLWALK3R** [sbussetti/deluge-siphon#15]
Trying to add torrents now fails 

http://v.lel.ovh/1428504184 (Video demo of issue)

**Comment by sbussetti** [comment]
This is an error from your deluge server that is bubbling back up. Make sure your deluge server is up to date: 
http://dev.deluge-torrent.org/ticket/2737

That said - i realize i should update the extension to make it more clear that the error is from your deluge server, not from my extension.

**Comment by MLWALK3R** [comment]
I'm running the latest Deluge. looks like the fix is due in v1.3.12
```bash
deluge-web: 1.3.11
libtorrent: 0.16.17.0
```

**Comment by sbussetti** [comment]
Fair enough. If you left any issues or feedback on the extension's google page would you mind updating your post with the resolution to this issue?  Much appreciated and feel free to reach out any time.
