### ISSUE TITLE
no rightclick context menu options

### ISSUE THREAD

**Issue by chenks** [sbussetti/deluge-siphon#16]
is this extension still supported?
i have a problem, just installed it (chrome 64bit mac).
i have the context menu right click enabled, but whenever i right click on a torrent link (standard or magnet) i see no option to send it to my deluge server.

so what's the problem?

**Comment by sbussetti** [comment]
Do you have your server url etc configured in the options?  Also do me a favor -- uncheck and then re-recheck the box for right click (context menu) in the options.  There may be a bug with the default settings (which I'll provide a update for).

**Comment by chenks** [comment]
yes, server (along with port) and webui password filled in.
i have unticked and reticked them.
where should i see the options in the context menu? as nothing shows up anywhere

**Comment by sbussetti** [comment]
http://screencast.com/t/krWrd4K2R4o

Perhaps try restarting Chrome?  I haven't run into this before but am happy to help resolve it.

**Comment by chenks** [comment]
ok, that seems to have resolved it.
(unticking and reticking).
at first (after doing the above) i was only seeing the option when right-clicking on an actual torrent link, but now it is showing on all links now.

**Comment by sbussetti** [comment]
Thanks for the extra info.  it sounds like there’s a regression where the default values on first install aren’t being respected.  I’ll look into fixing that!!


~ Steve Bussetti

On June 29, 2015 at 9:52:00 AM, chenks (notifications@github.com) wrote:

ok, that seems to have resolved it.
(unticking and reticking).
at first (after doing the above) i was only seeing the option when right-clicking on an actual torrent link, but now it is showing on all links now.

**Comment by chenks** [comment]
any chance you could also (at some point) add so you can see what torrents are downloading and let you start/stop/pause them?

like the other deluge extension (remote deluge) does?

**Comment by sbussetti** [comment]
#17
