### ISSUE TITLE
allow status and control of torrents

### ISSUE THREAD

**Issue by sbussetti** [sbussetti/deluge-siphon#17]
Investigate fasibility of viewing status and stopping/starting downloading torrents from within extension.

This is actually (implementation-wise) similar to the request to add labels -- it'll have to get done using the newer Rich Notifications API in Chrome.

**Comment by chenks** [comment]
labels would also be good to have (as you noted in the original post).
that means i get could manually add and let sonaar and couchpotato deal with it automatically after i had manually added the torrent.

**Comment by sbussetti** [comment]
Yup -- #12  I've been super busy and haven't been developing new features for this extension but I plan on digging back into it again to implement this set of features.  There was a new api in chrome introduced several months ago that allows a lot of this functionality in a non-hacky way, which is great.

**Comment by sbussetti** [comment]
Closing this -- I don't plan on adding status / control of torrents as this duplicates the functionality of the web-ui and doesn't provide any additional value you couldn't get from just going to Deluge.  Other items have been added.
