### ISSUE TITLE
Deluge server url

### ISSUE THREAD

**Issue by petroul** [sbussetti/deluge-siphon#19]
Dear all,
I don't get access to my Deluge daemon with deluge-siphon while access from Deluge on Windows works right away.
What to enter as deluger server url?
Default is: "http://localhost/user/deluge"
"http://192.168.0.121:58846/deluge" does not work (deluge is user name)

Every hint is welcome. Thanks in advance

**Comment by sbussetti** [comment]
Simply use the same URL you use to view the Deluge web interface directly!

**Comment by petroul** [comment]
Steve,

Please advice it does not work in my configuration. The same URL will start
the web ui.

THanks in advance!

[image: Inline image 1]

**Comment by sbussetti** [comment]
Please advise that github does not allow for inline images in messages -- you have to attach them directly via the website or link to them.

Can you provide any more details about the issue?  When you click on the DelugeSiphon icon in your plugin bar, is there a link to "Web UI" available?  If you click on it what happens?

**Comment by petroul** [comment]
DearSteve,

The Web UI start, I enter password and next can load manually (via browse)
torrents.

In case I download torrents from rutracker:
- In case I access a .torrent file, there is no option when right clicking
(regular expression is \.torrent)
- In case I also enabled "enable left clicking", Chrome informs me it
cannot be opened.
- Right clicking on a link on a torrent site, tells me this is not a
torrent.

In case I download torrents from kickass:
- Right click does work!

So it is all related to rutracker. Any clue how to solve this?

**Comment by sbussetti** [comment]
Thanks for the report.  I'll investigate that site.

**Comment by sbussetti** [comment]
Hey uh, I think your problem is that you're not clicking on torrent links.  I just added a magnetlink from that site via the extension no problem, but I had to drill down through several pages to actually get to the real link.  This extension does not drill into pages for you and try to find the links.  That's up to you!
