### ISSUE TITLE
No longer working on Gazelle-based trackers

### ISSUE THREAD

**Issue by joeczucha** [sbussetti/deluge-siphon#20]
Thanks for your work on this plugin, it's really handy.

However, it no longer seems to work with Gazelle-based trackers. The DL link is in the following format: 

/torrents.php?action=download&id=30624983&authkey=b46e831708666276b9e9eb9aa5b1ab12&torrent_pass=1zv68o5tnjy6lhxf1ltt2mzl22jmrd34

but I receive a notification saying that it is "not a valid torrent"...

**Comment by sbussetti** [comment]
If possible:

1. Turn on debug logging, and open the background console and paste me the result of this issue?
( Go to Deluge Siphon options > ensure "Enable console debug logging" is turned on > Follow the link to the Extensions page > reload the page > click the "background page" for this extension to open the debug console.)  Then open a new tab, and try and add a torrent.  Please provide any messages from the console here.

2.  After that restart your deluge server and deluge web ui and let me know if that resolves anything.

The "Not a valid torrent" error from deluge-siphon is raised when your deluge server returns no response or a non-200 response when this extension asks it to validate the torrent.  It's not actually an error from this extension.

**Comment by joeczucha** [comment]
Thanks for investigating :)

    extensions::messaging:316 Uncaught TypeError: Cannot read property 'name' of undefined
    sendMessageImpl @ extensions::messaging:316
    (anonymous function)  @ VM647 extensions::runtime:115
    target.(anonymous function) @ extensions::SafeBuiltins:19
    (anonymous function)  @ VM635 extensions::binding:57
    target.(anonymous function) @ extensions::SafeBuiltins:19
    (anonymous function)  @ VM635 extensions::binding:385
    site_init @ content_handler.js:291
    handle_visibilityChange @ content_handler.js:100

Restarting the server and webui had no effect :(

**Comment by sbussetti** [comment]
What you pasted is a benign error from the web-console.  Can you reproduce the issue but give me the output from the background page console as described in my previous comment?

**Comment by joeczucha** [comment]
Apologies, I didn't realise that I had to enable "developer tools" after following the link to the extensions page so the "background page" link wasn't showing.

    handleMessage Object {id: "gabdloknkpdefdpkkibplcfnkngbidim", url: "https://what.cd/torrents.php?id=73080712", tab: Object, frameId: 0}frameId: 0id: "gabdloknkpdefdpkkibplcfnkngbidim"tab: Objecturl: "https://what.cd/torrents.php?id=73080712"__proto__: Object ["storage", "get", "link_regex"]
    controller_actions.js:404 handleMessage Object {id: "gabdloknkpdefdpkkibplcfnkngbidim", url: "https://what.cd/torrents.php?id=73080712", tab: Object, frameId: 0}frameId: 0id: "gabdloknkpdefdpkkibplcfnkngbidim"tab: Objecturl: "https://what.cd/torrents.php?id=73080712"__proto__: Object ["storage", "get", "enable_keyboard_macro"]
    controller_actions.js:404 handleMessage Object {id: "gabdloknkpdefdpkkibplcfnkngbidim", url: "https://what.cd/torrents.php?id=73080712", tab: Object, frameId: 0} ["storage", "get", "enable_leftclick"]
    controller_actions.js:30 delugeConnection https://what.cd/torrents.php?action=download&id=xxxxxxxx&authkey=xxxxxxxx08666276b9e9eb9axxxxxxxx&torrent_pass=xxxxxxxxnjy6lhxf1ltt2mzlxxxxxxxx what.cd undefined
    controller_actions.js:50 what.cd and https://lutin.seedboxes.cc/xxxxxxxxxxxxxx/deluge vs https://lutin.seedboxes.cc/xxxxxxxxxxxxxx/deluge
    controller_actions.js:352 Requesting link... 1500 x1608982286 request yes
    controller_actions.js:126 true "7a2d98830bf8892a246a4d4d366160e918326980"
    controller_actions.js:216 Server config Object {download_location: "/home/disk5/xxxxxxxxxxxxxx/torrents/downloads"}
    controller_actions.js:259 _downloadTorrent DLPRAMS {"method":"web.download_torrent_from_url","params":["https://what.cd/torrents.php?action=download&id=xxxxxxxx&authkey=xxxxxxxx08666276b9e9eb9axxxxxxxx&torrent_pass=xxxxxxxxnjy6lhxf1ltt2mzlxxxxxxxx","__cfduid=df6b240bf93c270dbc8d9ddaf5eab2d0d1453398702;session=FCmQM%2FuYTS4c74tJZFMEjqr%2BplyMBUqS9iE8b82NdtFHGo1Jo3qZpCMwT4vyvMDztgszxWBZsEKlGuYyzisYg86VcD%2Fnz73iHTrNDEtZPfCJeDNJNsdqUmwVrQc4IXMbbKtCVaGYd4U%2BINadLQxHkQ%3D%3D"],"id":"-17002"}
    controller_actions.js:266 _downloadTorrent__callback /tmp/delugeweb-FBq83r/torrents.php?action=download&id=xxxxxxxx&authkey=xxxxxxxx08666276b9e9eb9axxxxxxxx&torrent_pass=xxxxxxxxnjy6lhxf1ltt2mzlxxxxxxxx
    controller_actions.js:285 checklink XMLHttpRequest {} Object {id: "-17003", result: false, error: null}
    controller_actions.js:352 Not a valid torrent: https://what.cd/torrents.php?action=download&id=xxxxxxxx&authkey=xxxxxxxx08666276b9e9eb9axxxxxxxx&torrent_pass=xxxxxxxxnjy6lhxf1ltt2mzlxxxxxxxx -1 x1608982286 error yes
    controller_actions.js:404 handleMessage Object {id: "gabdloknkpdefdpkkibplcfnkngbidim", url: "https://what.cd/torrents.php?id=73080712", tab: Object, frameId: 0} ["storage", "get", "link_regex"]
    controller_actions.js:404 handleMessage Object {id: "gabdloknkpdefdpkkibplcfnkngbidim", url: "https://what.cd/torrents.php?id=73080712", tab: Object, frameId: 0} ["storage", "get", "enable_keyboard_macro"]
    controller_actions.js:404 handleMessage Object {id: "gabdloknkpdefdpkkibplcfnkngbidim", url: "https://what.cd/torrents.php?id=73080712", tab: Object, frameId: 0} ["storage", "get", "enable_leftclick"]

**Comment by sbussetti** [comment]
Thanks for the tip! Forgot about that as well.  I'm investigating.

**Comment by joeczucha** [comment]
No problem :) I had to obfuscate some details from the above but if you need any further information feel free to drop me an email... 

I initially thought it might be an issue with sites using https but I've tried a couple more and they are working fine. 

Thanks again for checking.

**Comment by sbussetti** [comment]
Okay, can't specifically isolate the issue, but I did have a minor cleanup update locally that I just released.  It may help but I'm not certain.

That said, can you verify if your server is out of free space?  This step can fail when deluge is out of space and so can't make a temporary copy of the torrent file.

**Comment by joeczucha** [comment]
I checked and the server is fine, othersites (http and https) seem to be working fine it's just WCD that's having trouble. Thanks for looking anyway, I'll try the new version tomorrow.

**Comment by sbussetti** [comment]
Hrm strange.  I'm also on WCD and things are working fine for me using the version I just released.
