### ISSUE TITLE
Torrent download timeout (5000ms) is too short in some cases

### ISSUE THREAD

**Issue by courtarro** [sbussetti/deluge-siphon#21]
Today I have been getting COMMS ERROR messages from DelugeSiphon. This happens during the "Download Torrent" step, which is the third `/json` query that DelugeSiphon makes to deluge-web.

As it turns out, my Comcast connection is currently buggy because Comcast's primary DNS server is down. Thus, deluge-web takes about 5.5 seconds to get a successful DNS result from the secondary DNS server in order to perform the "Download Torrent" step. The `.torrent` file download is nearly instantaneous after that, but DelugeSiphon has already timed out waiting for the `/json` download method to finish.

Bumping the `xmlHttpTimeout` duration in `ajax()` within `utils.js` to 10000ms fixed my problem. The deluge-web process took its normal 5.5 seconds, and DelugeSiphon completed the "Add Torrent" step afterward, which is obviously necessary to complete the process.

The takeaway is that the 5000ms timeout was too short for my situation. I had to lengthen it manually within the extension code. Maybe this could be a configuration parameter, or just be lengthened in general?

Secondary suggestion: the failure message that resulted from this issue was pretty cryptic, so it took me a while to track down what was causing it. I would suggest adding, related to `xmlHttpTimeout` in `utils.js`, a notification that specifically tells the user that deluge-web took too long to respond to a request.

**Comment by transiti0nary** [comment]
I'm experiencing the same error but changing xmlHttpTimeout to 10000 did not fix the issue

**Comment by sbussetti** [comment]
Any other details about your issue?  Comms Error can mean a lot of things and generally just is a result of the ajax request failing -- it's not necessarily a timeout issue.  if you enable debug logging from the options and open the background page console, there should be more details.

**Comment by sbussetti** [comment]
version 0.70.0 is now out. please open a new issue if you're still experiencing troubles after update
