### ISSUE TITLE
Feature request: Specify download location

### ISSUE THREAD

**Issue by simonwolton** [sbussetti/deluge-siphon#24]
It'd be really cool to be able to manually specify where torrents end up after downloading. 

I understand that Siphon checks 'Download to' and 'Move completed to' fields, but I often manually specify sub directories for the latter field.

**Comment by sbussetti** [comment]
Done.  Just released version 0.70.0 on the webstore.  There is now an "add with options" method that will let you specify move-to and download locations as needed

**Comment by Hideki-85** [comment]
Please allow the new "add with options" feature to be disabled in the options for those of us who liked not having to go further into a context menu to add a torrent.

**Comment by sbussetti** [comment]
@Hideki-85 you got it.  That will be a configurable option in the new version I'm releasing today.
