### ISSUE TITLE
Failing on certain magnet links

### ISSUE THREAD

**Issue by jchiellini** [sbussetti/deluge-siphon#29]
I do not know if this has to do with the recent 0.7.0 release of this chrome extension, but I have suddenly started to see silent failures when adding torrents using a magnet link. Deluge siphon will show a notification but the torrent will never show up in my deluge client list. Has anyone else seen this issue?

**Comment by sbussetti** [comment]
You're totally right, and it is -- I missed something QA-ing the new version.  Working on a fix right now.

**Comment by sbussetti** [comment]
Fix published, update incoming.  If you don't get it within the hour, restart chrome to force it.

**Comment by jchiellini** [comment]
@sbussetti Thank you so much for the quick response. Love this little app! I use it daily.

**Comment by sbussetti** [comment]
![you-got-it-dude-michelle-reaction-gif-on-full-house](https://cloud.githubusercontent.com/assets/913361/20527112/268cea70-b095-11e6-8b4e-7ad83dac1ddb.gif)
