### ISSUE TITLE
magnet link broken for deluge 2.0.0dev

### ISSUE THREAD

**Issue by xuefer** [sbussetti/deluge-siphon#30]
it used to work with exactly same version of deluge but older delugesiphon, but now after upgraded delugesiphon it breaks.

popup says "Your verison of deluge [2.0.0dev730] does not support magnet links. Consider upgrading"

**Comment by sbussetti** [comment]
What version of delugesiphon are you on? I'm already releasing bugfix versions.

**Comment by xuefer** [comment]
0.70.1

**Comment by sbussetti** [comment]
I got it -- I'm removing the check for version in my extension completely -- it can't handle complex version #'s like 2.0.0dev730 -- all it's trying to do is check that you have at least version 1.3.3 which introduced magnet support, but that was so long ago, everyone is updated by now.

Just pushed 0.70.2 to the store that just removes this check, it's needless now.

**Comment by sbussetti** [comment]
closing as fixed.
