### ISSUE TITLE
Add torrent pop-up not showing on thepiratebay.org

### ISSUE THREAD

**Issue by Scorcher7986** [sbussetti/deluge-siphon#31]
Added torrents through the magnet link on most websites will pop-up the add torrent box where you confirm the settings and click add. However, on thepiratebay, doing so will darken the background of the webpage but keep the middle section lit up without the pop-up showing. Presumably, this is because the middle section of thepiratebay is showing on top of the pop-up box, which explains why it isn't darkened like the rest of the page.

**Comment by sbussetti** [comment]
Fixed in ver 0.70.3
