### ISSUE TITLE
Chrome extension always shows DS start page on startup

### ISSUE THREAD

**Issue by chiamarc** [sbussetti/deluge-siphon#33]
I don't know what version this started with but Deluge Siphon start page shows up in a tab everytime I start or restart Chrome.  Occurs on Linux **and** Windows.

**Comment by sbussetti** [comment]
@chiamarc I've been pushing some new versions lately -- I just pushed two today.  It pops that window every time a new version is installed, which has been pretty frequent lately because I've had more time to develop.

**Comment by chiamarc** [comment]
OK, I'll keep an eye on it.  Thanks!

**Comment by sbussetti** [comment]
Yeah, can see how that'd be annoying though, I'll see if I can make it only show up on major updates and not just little bugfixes.

**Comment by sbussetti** [comment]
-- pushing a version now that does the above -- only pops the installed page on major versions, not on minor bugfix updates.  Enjoy and thanks for using my extension.
