### ISSUE TITLE
Console verbosity

### ISSUE THREAD

**Issue by EduardoOliveira** [sbussetti/deluge-siphon#34]
Hi
I'm a developer, I was working when I noticed a lot of "unknown" console logs, WTF!?.
It was the siphon.... Can you please remove the console logs while not in debug mode? Or add some kind of blacklist to prevent siphon to inject the script in some domains...

Thank you :)

**Comment by sbussetti** [comment]
Apologies for that -- just forgot to clear out the frontend logging on this last version, will fix soon.

**Comment by sbussetti** [comment]
fixed.

**Comment by EduardoOliveira** [comment]
Thank you :).
Just a note for future cases, I just realized later, in chrome if you right click the log output you can hide all the output from a certain script.
