### ISSUE TITLE
Always starts with default prefs

### ISSUE THREAD

**Issue by flashbackpa** [sbussetti/deluge-siphon#35]
Everytime i start using siphon, it starts with default prefs, it tries to connect to localhost instead than try to connect to the host i wrote in prefs. Than i have to  revert to default prefs and rewrite my own.

**Comment by sbussetti** [comment]
That's a strange one.  the extension stores its prefs in localStorage -- do you block or reset that or anything between sessions?

**Comment by sbussetti** [comment]
Roger that, I will work to reproduce and get this fixed asap.  Thanks for using my extension and thanks for reporting this issue!

**Comment by clementleger** [comment]
What a quick response :) Tell me if you need some debug information, etc.

**Comment by sbussetti** [comment]
I have a guess what  it is -- gonna push an adjustment later tonight.  I'll let you know once it's in the wild so  you can check... if that doesn't do it I'll prolly ask for some console log info.  stay tuned.

**Comment by sbussetti** [comment]
@clementleger -- just pushed 0.70.6.  Let me know if you have better luck with your settings
@flashbackpa -- I'm still not really clear on why your settings wouldn't be saving unless you have localStorage disabled.  Can you check Settings -> Privacy -> Content Settings?  "Allow local data to be set" must be enabled for my extension to save its settings.

**Comment by clementleger** [comment]
@sbussetti : Still no luck... I have checked to be sure and localstorage is allowed.
I'm using chromium 	55.0.2883.75 (Developer Build) Built on 8.6, running on Debian 8.6 (64-bit)
and deluge. 
Is there a way to try older delugesiphon version manually ? I tried cloning it and loading as a local extension but it did not work (settings were never saved)

**Comment by sbussetti** [comment]
@clementleger -- yeah you need to build the extension before loading it.  To do so:

make sure you pull the latest (i just pushed a small change to help you test), then.

`npm install -g gulp`   (if you don't already have gulp installed)
`cd path/to/deluge-siphon`
`npm install`
`gulp build`

that'll create a `build/` folder in the project.  you can then "load unpacked extension" and point it at build/, not at the project root.

Once installed, go to options, enable debug logging and reload the extension.

After that, just open the [background page] inspector from the link on my entry on the extensions:// page and then go through your use case -- change some settings, then try to download something.  If possible, also open the console inspector on the actual page your using the extension and send me the log output from there too.

Really appreciate the help.

**Comment by clementleger** [comment]
Ok, I think I got it... When deluge-siphon connects to deluge, deluge returns in formations with daemon port and ip (at least, I think). And the IP is 127.0.0.1. So it seems to be more of a deluge configuration problem rather than deluge-siphon :) Sorry for bothering you ! 
By the way, I fixed a small error message.
Thanks for your help !
