### ISSUE TITLE
Unsetting "move completed to" does not override server default

### ISSUE THREAD

**Issue by FVGAZI** [sbussetti/deluge-siphon#39]
Everything worked perfectly at first. 
Now it errors that the torrent was already added and it adds to the default directory regardless where I tell it. Huge pain since by the time I get back to deluge I have to move storage.
Windows 10 64bit
edit: It appears to be adding to the directory I choose, but then moving to the default "Move completed to" directory I have set in deluge. Even though I unselect this option in the delugesiphon popup.
![2017-01-15_11-48-24](https://cloud.githubusercontent.com/assets/19436076/21965227/d8b7147a-db18-11e6-8dda-6c0ac602eda8.png)
![2017-01-15_11-48-35](https://cloud.githubusercontent.com/assets/19436076/21965228/d8b76498-db18-11e6-9851-9b13173bd3c1.png)

**Comment by sbussetti** [comment]
Yeah -- right now that option only overrides if there is something set there.  I didn't think of the case where you'd wanna temporarily turn it off.

Will fix.

**Comment by sbussetti** [comment]
Just released version 0.71.0 that should resolve this issue.  Reopen if you still have problems.
