### ISSUE TITLE
DelugeSiphon & IPTorrents.com *STILL* Don't Get Along

### ISSUE THREAD

**Issue by SoonerLater** [sbussetti/deluge-siphon#4]
Issue #2 is not resolved or IPTorrents has changed their system again.

https://github.com/sbussetti/deluge-siphon/issues/2#issuecomment-15028968

**Comment by shanep2300** [comment]
I think they might have changed something again. I can't get it to work on 0.6.66

**Comment by ender84** [comment]
I'll add to this. I get an error when trying to use the Right-Click option.
Error: 'module' object has no attribute
'_parse'

Here is a screenshot.
![capture](https://cloud.githubusercontent.com/assets/11813480/17491266/dfd17718-5d74-11e6-9e57-4f46cb024adc.JPG)

**Comment by sbussetti** [comment]
Thanks. I'm working on a new major version that rewrites most of the
extension to support folks' requests for labels and a few other things.
I'll be sure to test this thoroughly.

-- 
Steve Bussetti
