### ISSUE TITLE
When delugesiphon is active some links are not displayed

### ISSUE THREAD

**Issue by matofesi** [sbussetti/deluge-siphon#40]
I'm not sure if this is only our company webpage or is there more, but when I load this page:

[http://www.unitedbeverages.pl/strona_glowna.html](http://www.unitedbeverages.pl/strona_glowna.html)

with delugesiphon active there is an ad displayed at the center of the page but there is no "close" button that should be displayed in top right of the ad by this code:

`<a href="#close-modal" rel="modal:close" class="close-modal ">Close</a>`

When I do the inspection I can see this:

`.jquery-modal .modal a.close-modal {`
`    display: none;`
`}`

If I disable delugesiphon everything goes back to normal - close link is displayed correctly.

**Comment by sbussetti** [comment]
hey what are the odds, we both use jquery-modal ;o)

I've patched the copy of jquery-modal I use to scope it's CSS within a unique identifier to avoid this.
