### ISSUE TITLE
Automatic Label Settings

### ISSUE THREAD

**Issue by Zym3x** [sbussetti/deluge-siphon#42]
Love your extension! works great
could you in options add new torrents with label automagicly
should be pretty easy..

**Comment by sbussetti** [comment]
@Zym3x bump

**Comment by Zym3x** [comment]
Hello sorry for late reply,
Yeah exactly like that!
Always add label "X" to torrents
couchpotato has that function so i know it is at least possible

This is a bit of a reach, but maybe you could add specific labels if torrent includes a word
like all torrents with "yify" inside name get's a "movie" label.

**Comment by sbussetti** [comment]
Okay I understand now.  That's a pretty good idea and not too hard to implement actually.  I'll get it in soon @Zym3x

**Comment by Zym3x** [comment]
Cool to hear :D

**Comment by OmgImAlexis** [comment]
@sbussetti it'd also be great to see a default label. I only use this to add shows to deluge so it'd be great if I could just enable "tv" as my default this would then allow me to add files by clicking the link instead of having to go through the right click menu.

**Comment by sbussetti** [comment]
@Zym3x and @OmgImAlexis Just released version 0.71.0 that adds the ability to set a default label.  Keeping this open because I'm still working on adding the ability to add labels based on matching the name of the torrent in an upcoming release.

**Comment by OmgImAlexis** [comment]
It's working well.

I did notice there's an empty option between each select for some reason though.

```
<select id="default_label" class="option_field">
    
    <option value=""></option>
    <option value="movie">movie</option>
    
    <option value=""></option>
    <option value="music">music</option>
    
    <option value=""></option>
    <option value="other">other</option>
    
    <option value=""></option>
    <option value="tv">tv</option>
    
    </select>
```

**Comment by sbussetti** [comment]
0.71.3 published should fix this
