### ISSUE TITLE
Connection Info Not Displaying

### ISSUE THREAD

**Issue by AncientVale** [sbussetti/deluge-siphon#43]
I am having an issue where deluge siphon is not showing the connection options, so I cannot actually configure it to see my deluge install. See the pic below:

http://imgur.com/ivuVmme

**Comment by sbussetti** [comment]
I'll have a fix pushed shortly that'll autoupdate. Please stand by.

~ Steve

**Comment by sbussetti** [comment]
patch on it's way, 0.70.8 should update soon.

**Comment by Deams51** [comment]
0.70.8 here and Chrome 56.0.2924.76
Still got the issue. :)

**Comment by sbussetti** [comment]
0.70.9 on its way

**Comment by Deams51** [comment]
A bit more info from the console:  
```
options.js:254 Uncaught TypeError: Cannot read property 'length' of undefined
    at options.js:254
    at options.js:286
```

Also, it seems reinstalling made the trick.
