### ISSUE TITLE
Deluge Siphon CSS spilling over into unrelated page CSS and breaking

### ISSUE THREAD

**Issue by nicholascowan** [sbussetti/deluge-siphon#44]
When I use [Sonarr](https://github.com/Sonarr/Sonarr) the modal CSS is being overwritten by injected stylesheets within Deluge Siphon, I think the latest changes to the CSS where the parent selector was removed is causing undesirable effects.

Either way, I had to disable Deluge Siphon until this is resolved.

**Comment by kolinger** [comment]
I have same problem. Deluge injecting set of styles to .modal class. This will result in broken websites. Disabling deluge fixes issue.

![deluge-injected-styles](https://cloud.githubusercontent.com/assets/1590930/22416180/0f03bfb4-e6cd-11e6-90df-a2a05f391402.PNG)

**Comment by sbussetti** [comment]
This should be fixed in 0.70.9 - can you verify?

~ Steve

**Comment by bjammin** [comment]
I also have this problem with the .modal class being injected and breaking various web sites.

Also happening in 0.70.9

**Comment by sbussetti** [comment]
Ugh -- somehow (by somehow I mean I made a mistake), the original jquery-modal css got into the package and not my modified copy that scopes all the selectors under a unique identifier.

I just pushed a new version with what I thought was in there all along.  Sorry folks.

**Comment by kolinger** [comment]
Problem solved for me (0.71.0)

**Comment by sbussetti** [comment]
@kolinger thanks for reporting fixed status.  Again apologies for the oversight.  I did basically a total rewrite for 0.7x and I'm still getting things stabilized.

**Comment by nicholascowan** [comment]
@sbussetti @kolinger Thanks for quick resolution.

**Comment by bjammin** [comment]
Fixed for me in 0.71 too.  Thanks for the quick response!
