### ISSUE TITLE
WebUI Login need manual input

### ISSUE THREAD

**Issue by enri1357** [sbussetti/deluge-siphon#45]
I have input the password in option, but every time I have to login once on each browser start up.

I see there are * in the option password field, but I am not sure if there should be an OK/Confirm input field.

Anyway, it works when I input the  password manually. Just want to report this bug

**Comment by sbussetti** [comment]
@enri1357 yeah so, currently you are not logged into the webui until after you've added a torrent -- login happens as a side effect of adding.

In other words, if you go to the webui first, it'll ask for a password, but if you add a torrent first, then you'll be logged in when you go to the webui later.  

last time I messed with this Chrome was a little weird about letting me auto-log you into the webui before you add a torrent, but that was a long time ago, so I'll see if it's more agreeable now.

**Comment by enri1357** [comment]
In fact, my original question is it don't let me add task before logging in

Now I found that it seems the settings of password only applied after a
complete stop of all chrome process, then relaunch it. I try it today a few
times, I still not 100% sure if it behave like what I mention right now

i.e. It is okay if it let me auto login

**Comment by sbussetti** [comment]
@enri1357 I don't see exactly what you're reporting on my end, but I do see some improvements I could make around login that should help.  I started working on them yesterday and will have an update soon.

**Comment by sbussetti** [comment]
Just published version 0.71.1 that should resolve this issue.  Reopen if you still have problems.
