### ISSUE TITLE
Constant Connection Error Popup

### ISSUE THREAD

**Issue by gte619n** [sbussetti/deluge-siphon#47]
I'm on a network outside of the location of my server. The plugin is constantly popping up connection error messages. These mesages are the Chrome Notification popups in the lower right corner. This is new behavior.

**Comment by chiamarc** [comment]
I can confirm this behavior on Chrome on Ubuntu as well.  For now I just disabled the extension.  I would not say this is a critical bug but it should be addressed sooner rather than later.

**Comment by sbussetti** [comment]
I pushed 0.71.3 -- @gte619n @chiamarc  can you let me know if it is still happening with that version once you get it?  Thanks and sorry for the trouble.

**Comment by gte619n** [comment]
No apologies necessary! You've got a great plugin!

**Comment by sbussetti** [comment]
Just pushed another update, 0.71.4 that should further improve this issue.   And thanks for using my extension.

**Comment by thehaxxa** [comment]
I'm noticing the same behaviour, anyway to add an option to disable connection messages for users on multiple networks? I'm on version  0.71.4 and the popups are persistent at work.

**Comment by sbussetti** [comment]
@thehaxxa yeah I have support for multiple connections in the works, but not complete yet.  I adjusted the messages to try and get a better idea what the issue is -- Thanks for the screenshots.  It's related to the auto-login logic I added to address #45 .  I'm going to make some more adjustments and push another update shortly.

**Comment by sbussetti** [comment]
Just put v 0.71.5 in the hopper.  It should reduce if not completely resolve this verbose notification issue.  LMK how it goes.

**Comment by gte619n** [comment]
Steve, pardon my ignorance, but is there a way to force chrome to update or
do we just have to wait?

**Comment by sbussetti** [comment]
@gte619n little bit of both.  I'll ping on this thread once Google tells me they are done scanning and publishing the update.  Once that's complete it gets pushed out pretty soon. 

Ways to force your chrome to update extensions (after I let you know that Google is done scanning my code):

A. Quit and restart Chrome (all windows)

B. Go to:  chrome://extensions/ and refresh the page with control/command + r

**Comment by sbussetti** [comment]
@gte619n okay, update is past the Chromey gatekeepers.  Should be down to you soon.
