### ISSUE TITLE
Not adding torrents 

### ISSUE THREAD

**Issue by FVGAZI** [sbussetti/deluge-siphon#49]
Failing to add since the past couple of updates.
![image](https://cloud.githubusercontent.com/assets/19436076/23982032/fcc8ff6c-09c7-11e7-8c5d-34b312709e13.png)
Was working just fine prior to v 0.71.4
I 'm currently v 0.71.5

**Comment by sbussetti** [comment]
@FVGAZI possible for you to enable debug logging, open the background page (follow the link from chrome://extensions for my app) and record the log messages listed there?

Uh alternatively, I've been trying to get on apollo for a while, but I haven't be able to get so I can't yet test this myself =/

**Comment by FVGAZI** [comment]
After a Windows update and a restart this afternoon, everything is working fine. I'm assuming the restart fixed the issue. If it happens again I will forward you the logs.
I have an invite to Apollo I'd like to give you, but...
![image](https://cloud.githubusercontent.com/assets/19436076/24028088/9cee0566-0a89-11e7-9ea9-229080d4bb1b.png)
I'll keep checking to see if it opens up.

**Comment by sbussetti** [comment]
No worries. I missed the initial crossover and I have been lurking on irc ever since. Thanks for using my extension!!!!
