### ISSUE TITLE
Web UI link missing

### ISSUE THREAD

**Issue by cpshoemake** [sbussetti/deluge-siphon#50]
There used to be a Web UI link when I clicked on the delugesiphon icon. With the latest update that is gone. I'm not sure if this is a bug or if the link was intentionally removed, but I miss it.

Other than that everything works great. Keep up the good work and thanks!

-Cliff

**Comment by softgripper** [comment]
Yep, Web UI missing.  It was a great feature.

**Comment by sbussetti** [comment]
@softgripper @cpshoemake Hah I just noticed it myself this morning.  Got lost in the shuffle with these other bugs.  To be totally frank I'm balancing this project with a huge push at my day job, and I didn't test this round of changes nearly as well as I should've.  Mea culpa.

I'm going to push out a fix resolving that and turning off the update notifications everyone seems to hate a little later today.

**Comment by sbussetti** [comment]
fixed 0.71.6

**Comment by cpshoemake** [comment]
Awesome! Thanks.
