### ISSUE TITLE
Not adding

### ISSUE THREAD

**Issue by FVGAZI** [sbussetti/deluge-siphon#51]
Happening again.
I enabled debug logging, but I'm not sure what you need from the background page?

**Comment by sbussetti** [comment]
@FVGAZI If you can:

1. enable debug mode
2. reload the extension (refresh the chrome://extensions page)
3. click [background.html] to pop the console
4. go to the site in question and try to add a torrent, resulting in the error
5. just copy and paste everything from the console and send it this way.

Follow up, does it happen everywhere or is it limited to the one site?

**Comment by FVGAZI** [comment]
It happens everywhere...

controller_actions.js:3Debug logging enabled
controller_actions.js:16new DelugeConnection
controller_actions.js:289_getSession valid Object
controller_actions.js:330_checkDaemonConnection Object
controller_actions.js:371_getDaemons__callback Object
controller_actions.js:386_getHostStatus de4f7d386caddf98f8675cc0d51a7db6ecc5c445
controller_actions.js:417_getHostStatus__callback Object
controller_actions.js:452_getConnectedDaemon__callback Connected Object
controller_actions.js:616_getServerConfig Object
controller_actions.js:633_getServerConfig__callback Object
controller_actions.js:1041[[[ RECEIVED MESSAGE ]]] Object
controller_actions.js:1041[[[ RECEIVED MESSAGE ]]] Object
controller_actions.js:1041[[[ RECEIVED MESSAGE ]]] Object
controller_actions.js:1041[[[ RECEIVED MESSAGE ]]] Object
controller_actions.js:1041[[[ RECEIVED MESSAGE ]]] Object
controller_actions.js:1041[[[ RECEIVED MESSAGE ]]] Object
controller_actions.js:1041[[[ RECEIVED MESSAGE ]]] Object
controller_actions.js:1041[[[ RECEIVED MESSAGE ]]] Object
controller_actions.js:1041[[[ RECEIVED MESSAGE ]]] Object
controller_actions.js:1041[[[ RECEIVED MESSAGE ]]] Object
controller_actions.js:125****> getTorrentInfo https://tehconnection.eu/torrents.php?action=download&id=90927&authkey=eebe5f8ad2e8da75836bb4cab90ceef9&torrent_pass=tmk576cl2m4ih20vnq5xdoqxi5hu5wc1 tehconnection.eu
controller_actions.js:289_getSession valid Object
controller_actions.js:330_checkDaemonConnection Object
controller_actions.js:344_checkDaemonConnection__callback Object Object
controller_actions.js:616_getServerConfig Object
controller_actions.js:633_getServerConfig__callback Object
controller_actions.js:251_getDomainCookies for tehconnection.eu
controller_actions.js:659_getPlugins__callback Object
controller_actions.js:684_getLabelInfo__callback Object
controller_actions.js:802_downloadTorrent getlabelinfo Array[2]
controller_actions.js:814_downloadTorrent__callback c:\windows\temp\delugeweb-590qac\Sharknado 4_ The 4th Awakens - 2016 (Blu-ray - x264 - 1080p).torrent
controller_actions.js:832_getTorrentInfo downloadlink c:\windows\temp\delugeweb-590qac\Sharknado 4_ The 4th Awakens - 2016 (Blu-ray - x264 - 1080p).torrent
controller_actions.js:842_getTorrentInfo__callback torrentinfo Object
controller_actions.js:1041 [[[ RECEIVED MESSAGE ]]] Object {method: "storage-get-link_regex"}
controller_actions.js:1041 [[[ RECEIVED MESSAGE ]]] Object {method: "storage-get-enable_keyboard_macro"}
controller_actions.js:1041 [[[ RECEIVED MESSAGE ]]] Object {method: "storage-get-enable_leftclick"}
controller_actions.js:1041 [[[ RECEIVED MESSAGE ]]] Object {method: "addlink-todeluge", domain: "tehconnection.eu", url: "https://tehconnection.eu/torrents.php?action=downl…ef9&torrent_pass=tmk576cl2m4ih20vnq5xdoqxi5hu5wc1", options: Object, plugins: Object}
controller_actions.js:1103 <<<< ADDLINK >>>> https://tehconnection.eu/torrents.php?action=download&id=90927&authkey=eebe5f8ad2e8da75836bb4cab90ceef9&torrent_pass=tmk576cl2m4ih20vnq5xdoqxi5hu5wc1 tehconnection.eu Object {Label: ""} Object {download_location: "E:\seeds\", add_paused: "true"}
controller_actions.js:83 ****> addTorrent https://tehconnection.eu/torrents.php?action=download&id=90927&authkey=eebe5f8ad2e8da75836bb4cab90ceef9&torrent_pass=tmk576cl2m4ih20vnq5xdoqxi5hu5wc1 tehconnection.eu Object {Label: ""} Object {download_location: "E:\seeds\", add_paused: "true"}
controller_actions.js:289 _getSession valid Object {id: "-16990", result: true, error: null}
controller_actions.js:330 _checkDaemonConnection Object {status: "Connected", port: 58846, ip: "127.0.0.1", host_id: "de4f7d386caddf98f8675cc0d51a7db6ecc5c445", version: "1.3.13"}
controller_actions.js:344 _checkDaemonConnection__callback Object {id: "-16991", result: true, error: null} Object {status: "Connected", port: 58846, ip: "127.0.0.1", host_id: "de4f7d386caddf98f8675cc0d51a7db6ecc5c445", version: "1.3.13"}
controller_actions.js:616 _getServerConfig Object {status: "Connected", port: 58846, ip: "127.0.0.1", host_id: "de4f7d386caddf98f8675cc0d51a7db6ecc5c445", version: "1.3.13"}
controller_actions.js:633 _getServerConfig__callback Object {add_paused: false, move_completed_path: "D:\tv_seeds\_unprocessed", download_location: "D:\tv_seeds\seeding", move_completed: false}
controller_actions.js:251 _getDomainCookies for tehconnection.eu
controller_actions.js:892 _addTorrentUrlToServer core.add_torrent_url ["https://tehconnection.eu/torrents.php?action=downl…ef9&torrent_pass=tmk576cl2m4ih20vnq5xdoqxi5hu5wc1", Object, Object]
controller_actions.js:227 Object {readyState: 0, status: 0, statusText: "timeout"} "timeout" "timeout"
(anonymous) @ controller_actions.js:227
f @ jquery-3.0.0.min.js:2
p @ jquery-3.0.0.min.js:2
controller_actions.js:913 _addTorrentUrlToServer__error []
(anonymous) @ controller_actions.js:913
f @ jquery-3.0.0.min.js:2
p @ jquery-3.0.0.min.js:2

**Comment by sbussetti** [comment]
It's getting all the way to asking your deluge server to request the torrent but then that last request is timing out.  Could be that your server is having trouble making outgoing requests. Can you make sure you can hit the site (techconnection.eu) from wherever deluge is running?

**Comment by FVGAZI** [comment]
I have no issues with the site or any others on this machine. 
Restarting windows fixed it yesterday. Which was odd. 
I've tried completely closing Chrome and clearing the cache, but it didn't help.

**Comment by sbussetti** [comment]
Are you running the deluge server on your windows desktop machine or another box?

**Comment by FVGAZI** [comment]
Windows desktop machine

**Comment by FVGAZI** [comment]
Same. I forgot to mention that it will every so often not even get to the error message and fail. If that makes sense? 
I caught it doing that this time...

background.min.js:6 *** Debug logging enabled ***
(anonymous) @ background.min.js:6
background.min.js:6 *** new DelugeConnection ***
background.min.js:6 _getSession valid Object
background.min.js:6 _checkDaemonConnection Object
background.min.js:6 _getDaemons__callback Object
background.min.js:6 _getHostStatus de4f7d386caddf98f8675cc0d51a7db6ecc5c445
background.min.js:6 _getHostStatus__callback Object
background.min.js:6 _getConnectedDaemon__callback Connected Object
background.min.js:6 _getServerConfig Object
background.min.js:6 _getServerConfig__callback Object
controller_actions.js:309 _getSession valid Object {id: "-16990", result: true, error: null}
controller_actions.js:350 _checkDaemonConnection Object {status: "Connected", port: 58846, ip: "127.0.0.1", host_id: "de4f7d386caddf98f8675cc0d51a7db6ecc5c445", version: "1.3.13"}
controller_actions.js:364 _checkDaemonConnection__callback Object {id: "-16991", result: true, error: null} Object {status: "Connected", port: 58846, ip: "127.0.0.1", host_id: "de4f7d386caddf98f8675cc0d51a7db6ecc5c445", version: "1.3.13"}
controller_actions.js:636 _getServerConfig Object {status: "Connected", port: 58846, ip: "127.0.0.1", host_id: "de4f7d386caddf98f8675cc0d51a7db6ecc5c445", version: "1.3.13"}
controller_actions.js:653 _getServerConfig__callback Object {add_paused: false, move_completed_path: "D:\tv_seeds\_unprocessed", download_location: "D:\tv_seeds\seeding", move_completed: false}
controller_actions.js:270 _getDomainCookies for freshon.tv
controller_actions.js:291 _getDomainCookies__callback freshon.tv uid=280674;pass=5a484cda888c77496c59266832007ab7;acopendivids=ul-notice-en,ul-notice-ro,info,thanks;acgroupswithpersist=nada
controller_actions.js:679 _getPlugins__callback Object {enabled_plugins: Array[2], available_plugins: Array[10]}
controller_actions.js:704 _getLabelInfo__callback Object {id: "-17001.2", result: Array[10], error: null}
controller_actions.js:822 _downloadTorrent getlabelinfo ["https://freshon.tv/download.php?id=195039&type=torrent", "uid=280674;pass=5a484cda888c77496c59266832007ab7;a…ul-notice-ro,info,thanks;acgroupswithpersist=nada"]
controller_actions.js:834 _downloadTorrent__callback c:\windows\temp\delugeweb-zl0hhv\TvT-Oasis.S01E01.1080p.AMZN.WEBRip.DD5.1.x264-DONNA.torrent
controller_actions.js:852 _getTorrentInfo downloadlink c:\windows\temp\delugeweb-zl0hhv\TvT-Oasis.S01E01.1080p.AMZN.WEBRip.DD5.1.x264-DONNA.torrent
controller_actions.js:862 _getTorrentInfo__callback torrentinfo Object {id: "-17003", result: Object, error: null}
controller_communicator.js:136 Lost connection: TypeError: Cannot read property 'postMessage' of undefined
    at Object.sendMessage (controller_communicator.js:133)
    at DelugeConnection.<anonymous> (controller_actions.js:1017)
    at l (jquery-3.0.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.0.0.min.js:2)
    at DelugeConnection.<anonymous> (controller_actions.js:139)
    at f (jquery-3.0.0.min.js:2)
    at p (jquery-3.0.0.min.js:2)

**Comment by FVGAZI** [comment]
It starts working again every time my machine gets rebooted. 
Which is not frequent.

**Comment by sbussetti** [comment]
Hey @FVGAZI  -- I haven't forgotten about this, just don't have a ton of time to work on the extension right now.  I do also see this issue appearing after a while -- you don't need to reboot your whole machine to fix it though, restarting Chrome should suffice.  I do still plan to fix this issue, so please bear with me.

**Comment by FVGAZI** [comment]
No worries. It's only been an issue once recently. I was starting to think that the Windows creators update fixed something. Along with breaking nssm haha.

**Comment by sbussetti** [comment]
Closing -- should've been fixed in an update along the way.  Reopen if not.
