### ISSUE TITLE
Start Daemon Error

### ISSUE THREAD

**Issue by rsngt** [sbussetti/deluge-siphon#52]
Hi

I am trying to use this extension but get an error saying the deluge server responded with error "startdaemon" anytime I try to add a torrent. I also see this error when I enable the extension after it's been disabled.

I am using the same URL that I successfully use to access the web front end on a remote Linux box. I am using the form "http://xxx.xxx.xxx.xxx:xxxx to specify IP address and port.

After right-clicking to "add" the torrent, I see a notification that says "adding torrent..." but this is followed by the error notification.

I have tried adding both magnet links and torrent file links with the same result.

I have searched the archive of errors and couldn't find anything similar.

Thanks
Stephen

**Comment by sbussetti** [comment]
Hey @rsngt for this to happen, your web-ui for deluge is running, but your deluge daemon is not, and my extension is unable to start it for you.

Please make sure your `deluged` is running and that your web frontend can communicate with it.

**Comment by sbussetti** [comment]
Closing -- should've been fixed in an update along the way.  Reopen if not.
