### ISSUE TITLE
Not working with PassThePopcorn

### ISSUE THREAD

**Issue by zimmertr** [sbussetti/deluge-siphon#53]
I really love this extension. Do you have any idea why it does not work for PassThePopcorn.me?

**Comment by sbussetti** [comment]
I use PTP myself all the time.  Can you give me any more info about what isn't working for you?

**Comment by zimmertr** [comment]
Whoa, I never realized you responded to me. Terribly sorry about that. I'm currently moving to Seattle so my server is in the trunk of my car. I'll let you know if I can replicate the issue again once everything is turned back on on the other side. Cheers!

**Comment by zimmertr** [comment]
Hi, Server is powered on once more. :)

What is the best way I can troubleshoot this for you? When I try and add a torrent from PTP, the first notification appears saying it is attempting to add the torrent to the client. After a time a second notification appears saying it failed to add the torrent. Debug logging to the console isn't providing any helpful error messages.

**Comment by sbussetti** [comment]
Closing -- should've been fixed in an update along the way.  Reopen if not.  PTP works just fine for me with 0.71.8
