### ISSUE TITLE
Not adding with deluge 1.3.14

### ISSUE THREAD

**Issue by scassarGitHub** [sbussetti/deluge-siphon#54]
Seems like not adding with deluge 1.3.14 like a lot of other chrome extension.

Restart of deluged and web do nothing.
Trying to add : https://www.t411.al/torrents/acronis-support-de-d-marrage-complet returns ok in the plugin but add nothing in deluge.

**Comment by octophetus** [comment]
Same here.  Errors out.

Object {readyState: 0, getResponseHeader: function, getAllResponseHeaders: function, setRequestHeader: function, overrideMimeType: function…}abort: function (e)always: function ()catch: function (e)done: function ()fail: function ()getAllResponseHeaders: function ()getResponseHeader: function (e)overrideMimeType: function (e)pipe: function ()progress: function ()promise: function (e)readyState: 0setRequestHeader: function (e,t)state: function ()status: 0statusCode: function (e)statusText: "timeout"then: function (t,r,i)__proto__: Object timeout timeout


Object {readyState: 0, getResponseHeader: function, getAllResponseHeaders: function, setRequestHeader: function, overrideMimeType: function…}abort: function (e)always: function ()catch: function (e)done: function ()fail: function ()getAllResponseHeaders: function ()getResponseHeader: function (e)overrideMimeType: function (e)pipe: function ()progress: function ()promise: function (e)readyState: 0setRequestHeader: function (e,t)state: function ()status: 0statusCode: function (e)statusText: "timeout"then: function (t,r,i)__proto__: Object "timeout" "timeout"





[callee: function, Symbol(Symbol.iterator): function]
callee
:
function ()
arguments
:
null
caller
:
null
length
:
0
name
:
""
prototype
:
Object
__proto__
:
function ()
[[FunctionLocation]]
:
controller_actions.js:839
[[Scopes]]
:
Scopes[2]
length
:
0
Symbol(Symbol.iterator)
:
function values()
arguments
:
(...)
caller
:
(...)
length
:
0
name
:
"values"
__proto__
:
function ()
__proto__
:
Object
constructor
:
function Object()
hasOwnProperty
:
function hasOwnProperty()
isPrototypeOf
:
function isPrototypeOf()
propertyIsEnumerable
:
function propertyIsEnumerable()
toLocaleString
:
function toLocaleString()
toString
:
function toString()
valueOf
:
function valueOf()
__defineGetter__
:
function __defineGetter__()
__defineSetter__
:
function __defineSetter__()
__lookupGetter__
:
function __lookupGetter__()
__lookupSetter__
:
function __lookupSetter__()
get __proto__
:
function __proto__()
set __proto__
:
function __proto__()

**Comment by sbussetti** [comment]
Please re-open if this is still an issue.
