### ISSUE TITLE
Performance drags after using a couple times

### ISSUE THREAD

**Issue by KarmaPoliceT2** [sbussetti/deluge-siphon#56]
Using this extension, it ends up bringing my chrome browser to a crawl after adding 4-5 torrents... lags input to the browser, lags page loads, etc... 

I know its this extension because as soon as i disable it everything goes back to normal... then when i re-enable it, everything is fine for the next few added torrents and then begins to slow everything down again... rinse, repeat

I have no idea how to debug an extension, so just let me know what you need to help you figure out more.

**Comment by OmgImAlexis** [comment]
Having the same issue here, had to disable the extension as Chrome keeps crashing after hitting 80% CPU usage on the Chrome Helper process for this extension.

**Comment by sbussetti** [comment]
I will check it out this week, I think there are some compatibility changes that need to be made for my extension wrt a recent update to chrome.

**Comment by theloafingone** [comment]
Running into the same issue here. Chrome is barely moving at this point after downloading a few in a row.

**Comment by bseishen** [comment]
+1

**Comment by sbussetti** [comment]
I can't repro this issue, and not with the current version.  Re-open if it is still an issue for you.
