### ISSUE TITLE
magnet link broken for deluge 2.0.0dev again

### ISSUE THREAD

**Issue by xuefer** [sbussetti/deluge-siphon#58]
siphon request
`
id :"-16992.undefined"
method : "web.get_host_status"
params : ["85ceb99eec4ec8fdcdae37278f3361eaf8a3ec23"]
`

respond
`{"id": "-16992.undefined", "result": ["85ceb99eec4ec8fdcdae37278f3361eaf8a3ec23", "Connected", "2.0.0.dev170705"], "error": null}`

but siphon says `failed to connect to deluge server Connected 2.0.0.dev170705`

This is latest git develop branch of deluge

**Comment by MrMxyzptlk** [comment]
I'm having the same issue as well.
