### ISSUE TITLE
ESET Internet Security download misdetected as a torrent

### ISSUE THREAD

**Issue by nyuszika7h** [sbussetti/deluge-siphon#60]
When I click "Free Download" on https://www.eset.com/int/, for some reason delugesiphon thinks it's a torrent (it's not) and tries to add it. It even says it was successful, but obviously nothing is added.

**Comment by jswclw** [comment]
Seeing same behavior just about everywhere the link is a "Download" link. Seems to be keying in on the "Download" title of the link. Thinking this could be temporarily worked around using the advanced setting for a RegEx to match torrent links.

**Comment by sbussetti** [comment]
fixed in 0.72
