### ISSUE TITLE
Make sending cookies optional

### ISSUE THREAD

**Issue by nyuszika7h** [sbussetti/deluge-siphon#63]
Please make sending cookies an option that's *disabled* by default and can be enabled manually (preferably on a per-tracker basis, but even just a simple switch would be appreciated for now). Some sites do not require cookies at all and detect the requests including cookies as the user browsing the site from the seedbox, which may be forbidden because it's a shared IP.

**Comment by sbussetti** [comment]
I'm making this option enabled by default to maintain the current settings for existing users.

Right now it's a toggle in options for globally sending, or not sending cookies.  Noted that this should eventually be a per-tracker blacklist, will add later.  Feel free to file another issue requesting that we add this tracker list.
