### ISSUE TITLE
Adding a blue box to all google websites (gmail, youtube, etc)

### ISSUE THREAD

**Issue by jruth85** [sbussetti/deluge-siphon#70]
After the latest update (Oct. 20 2018) the extension is adding the following element to all google pages:

<div id="delugesiphon-modal-gabdloknkpdefdpkkibplcfnkngbidim"></div>
#delugesiphon-modal-gabdloknkpdefdpkkibplcfnkngbidim {
    font-family: "Chrome Droid Sans", "Droid Sans Fallback", "Lucida Grande", sans-serif;
    color: rgb(209, 218, 229);
    position: relative;
    font-size: 16px;
    min-height: 250px;
    background: rgb(48, 70, 99);
    padding: 0px;
}

I've attached a screenshot of the issue. 
![capture](https://user-images.githubusercontent.com/44326849/47260085-6e2e9000-d469-11e8-87e9-4f2eec616a62.PNG)
![capture1](https://user-images.githubusercontent.com/44326849/47260086-6e2e9000-d469-11e8-941d-bcc70ffd7098.PNG)

**Comment by jruth85** [comment]
Update

It's actually doing it on all websites but I just didn't notice it because it's at the bottom for the other sites.

**Comment by sbussetti** [comment]
Verify you’re updated to 0.72.5 - a patched version was already released
with the fix. Sorry about that!

~
Steve
c: 917.930.0612

From: jruth85 <notifications@github.com> <notifications@github.com>
Reply: sbussetti/deluge-siphon
<reply@reply.github.com>
<reply@reply.github.com>
Date: October 20, 2018 at 4:16:28 PM
To: sbussetti/deluge-siphon <deluge-siphon@noreply.github.com>
<deluge-siphon@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
<subscribed@noreply.github.com>
Subject:  Re: [sbussetti/deluge-siphon] Adding a blue box to all google
websites (gmail, youtube, etc) (#70)

Update

**Comment by jruth85** [comment]
Aha. My bad. I saw that it had been updated and assumed I was running the latest version.

As you said 0.72.5 fixed the issue.  

Thanks!
