### ISSUE TITLE
Torrent already added

### ISSUE THREAD

**Issue by ghost** [sbussetti/deluge-siphon#79]
Hello,
using this extension but for some days I have a problem.
If I want to add torrent to Deluge, it shows me Torrent already added.
Tried it with new torrents, same result.
Tried reinstall extension.

delugesiphon 0.72.6

Any help?

**Comment by sbussetti** [comment]
Have you logged directly into your instance of deluge lately?  Can you log in and see if everything looks okay on that end?

**Comment by ghost** [comment]
yes and I login works fine

**Comment by sbussetti** [comment]
Is behavior limited on a particular site or do you get it no matter what site you try to add torrents from?
Are you using the left-click auto-detect, or are you using the right click to add via context menu?

**Comment by ghost** [comment]
Just found it doesn't work on specific site only.
https://tracker.aabbcc.net/download/454145

Tried it with another tracker and it works fine.

**Comment by sbussetti** [comment]
Thanks.  I'll check it out and release an update for compatibility with that site.

**Comment by sbussetti** [comment]
Actually -- that isn't a valid link at all.. it's just a parked domain.  There's not actually a torrent file there.

**Comment by sbussetti** [comment]
I think the error message is just misleading.
